name: Deploy docs
on:
  push:
    branches: [master]
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Build docs
        run: npm install && npm run build:docs
      - name: Build web demo
        run: npm --prefix=./tools/web-demo install && npm --prefix=./tools/web-demo run build && mv ./tools/web-demo/dist ./docs/web-demo
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
